* Rastache

Specific version of Rastache that adds dynamic context filling
functionality.

** Filler
Filler tag to fill the context from the template. A ={{+key::value}}=
tag in a basic template will fill the current context with the =value=
at position =key=.

Template:
#+BEGIN_SRC mustache
{{+name:: "Chris"}}
{{+company:: "<b>GitHub</b>"}}
* {{name}}
* {{age}}
* {{company}}
* {{{company}}}
* {{& company}}
#+END_SRC

Context:
#+BEGIN_SRC racket
#hash{}
#+END_SRC

Output:
#+BEGIN_SRC html
* Chris
*
* &lt;b&gt;GitHub&lt;/b&gt;
* <b>GitHub</b>
* <b>GitHub</b>
#+END_SRC

** License
   Copyright (C) 2015 Ronan-Alexandre Cherrueau

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public License
   as published by the Free Software Foundation; either version 2.1 of
   the License, or (at your option) any later version.

   This library is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with this library; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
   02110-1301 USA
